site_name: prodsys Documentation
theme: 
  name: material
  features:
    - content.code.copy

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_source: false
          filters:
            - "!^_[^_]"
            - "!^__[^_]"


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences