[tool.poetry]
name = "prodsim"
version = "0.1.0"
description = "A useful module for production system simulation and optimization"
authors = ["Sebastian Behrendt <sebastia.behrendt@kit.edu>"]
license = "MIT"
readme = ["README.md", "LICENSE"]

[tool.poetry.dependencies]
python = ">3.10, <3.12"
pydantic = "^1.10.7"
simpy = "^4.0.1"
fastapi = "^0.95.1"
uvicorn = {extras = ["standard"], version = "^0.21.1"}
deap = "^1.3.3"
simanneal = "^0.5.0"
gurobipy = "^10.0.1"
hydra-core = "^1.3.2"
pandas = "^2.0.0"
openpyxl = "^3.1.2"
plotly = "^5.14.1"
scipy = "^1.10.1"


[tool.poetry.group.test.dependencies]
pytest = "^7.3.1"


[tool.poetry.group.dev.dependencies]
basyx-python-sdk = "^0.2.2"
strawberry-graphql = "^0.171.1"
gymnasium = ">=0.26.3"
pm4py = "^2.7.3"


[tool.poetry.group.build.dependencies]
setuptools = "^67.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
